trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ciartifacts
    source: vijaymdwsynapse-ci-artifacts
    trigger: 
      branches:
      - main

  repositories:
  - repository: vijaymdwsynapse-workspacepublish
    type: git
    name: vijaymdwsynapse/vijaymdwsynapse
    ref: workspace_publish
    
stages:
- stage: deploy_to_dev
  displayName: 'Deploy to DEV'  # In DEV, excludes publishing to Synapse workspace as this is a manual publish step
  variables:
  - group: vijaymdwsynapse-release-dev
  - group: vijaymdwsynapse-secrets-dev
  jobs:
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'vijaymdwholserviceconnection'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'vijaymdwholserviceconnection'

- stage: deploy_to_stg
  displayName: 'Deploy to Stage'
  variables:
  - group: vijaymdwsynapse-release-stg
  - group: vijaymdwsynapse-secrets-stg
  jobs: 
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'vijaymdwholserviceconnection'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'vijaymdwholserviceconnection'
  - template: templates/jobs/deploy-synapse-workspace-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'vijaymdwholserviceconnection'
  # Integration tests
  #- template: templates/jobs/integration-tests-job.yml

- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: vijaymdwsynapse-release-prod
  - group: vijaymdwsynapse-secrets-prod
  jobs: 
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'vijaymdwholserviceconnection'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'vijaymdwholserviceconnection'
  - template: templates/jobs/deploy-synapse-workspace-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'vijaymdwholserviceconnection'